API_URL_PREFIX = '/api/v3'

ID_PATTERN = '^[0-9]+$'
PAGE_NUMBER_PATTERN = '^[0-9]+$'
INFO_HASH_PATTERN = '^[0-9a-fA-F]{40}$'  # INFO_HASH as string

MAX_PAGE_LIMIT = 1000
TORRENTS_PER_PAGE = 40
COMMENTS_PER_PAGE = 3